### ISSUE TITLE
0.2.18 InventoryNode.cs script error

### ISSUE THREAD

**Issue by Windy1563** [cstria0106/OneClickInventory#20]
0.2.18 업데이트 후 버그 발생
유니티 에러 로그 :
Packages\dog.miruku.ndcloset\Editor\InventoryNode.cs(3,7): error CS0246: The type or namespace name 'Codice' could not be found (are you missing a using directive or an assembly reference?)

Editor 폴더 InventoryNode.cs 파일 3번째줄 using Codice.CM.Common; 부분에서 에러 발생, 해당 문장 제거 후 정상 작동

**Comment by cstria0106** [comment]
해당 라인 제거하여 다시 릴리즈했습니다. 감사합니다.
