### ISSUE TITLE
옷장 off 했을때도 BlendShapes 변경 가능하게

### ISSUE THREAD

**Issue by leehojun456** [cstria0106/OneClickInventory#24]
옷장 off 했을때도 BlendShapes 변경 가능하게 했으면 좋겠습니다.

**Comment by cstria0106** [comment]
해당 기능이 필요한 이유를 말씀해주실 수 있나요?

**Comment by leehojun456** [comment]
튜토리얼 설명에 예시로 하이힐 쉐이프키가 있는데 기본적으로 0에 두고 활성화되어있을때 100으로 조절하게된다면
타 유저의 세이프티 설정 여부에 따라 다르게 보이지 않나요?
(ex 업로드할때 알몸으로 업로드하고 인게임에서 애니메이션으로 활성화 할 경우 인게임에서 특정유저에게 알몸으로 보이는 경우)

특히 chikubi 등의 세이프티의 경우에 문제가 생길 수 있다고 생각해서요

**Comment by leehojun456** [comment]
보통 유저들은 입혀진 상태에서 업로드하고 비활성화 버튼을 주로 쓰니까 비활성화 될때 블렌드 쉐이프도 변경되면 좋겠다 생각했습니다.

**Comment by cstria0106** [comment]
이해했습니다. 저는 업로드할때 기본적으로 옷을 입히고 모든 쉐이프키를 끄고 쉐이프키만 필요한 옷에서만 활성화되도록 하여서 그런 문제를 겪진 않았네요. 다만 하이힐 쉐이프키가 100이 필요한 옷을 입히고서 업로드하는 경우에 기본 값을 100으로 해야해서 기본 옷을 자주 바꾼다면 복잡해질수도 있을 것 같습니다. (이 경우는 fx 레이어에 기본 블렌드셰이프 애니메이션을 넣는걸로 해결할 수는 있습니다)

다만 해당 기능이 필요하여 구현한다고 했을때
예를 들어서 옷 A랑 옷 B가 비활성화 시 동일한 쉐이프키를 변경하려고 했을 때 어떤 것이 우선돼야하는 지 등 모호함이 있을 것 같습니다. 
또한 설정 값이 많아지면서 툴이 복잡해질수도 있을 것 같구요.
그래서 구현은 쉽게 가능하지만 정말 해야하는지 생각해봐야 할 것 같습니다.

참고로 알몸 같은 경우는 비어있는 알몸 오브젝트를 만들고 Inventory를 넣으면 chikubi 쉐이프키 등에 대응 가능합니다.

**Comment by leehojun456** [comment]
답변 감사합니다 잘 쓰고 있어요

**Comment by cstria0106** [comment]
잘 사용해주셔서 감사합니다. 잘안되는게 있으면 다시 질문해주세요!
