### ISSUE TITLE
Is there a way to set "Inventory" as submenu of user's custom menu?

### ISSUE THREAD

**Issue by gwanryo** [cstria0106/OneClickInventory#25]
![image](https://github.com/user-attachments/assets/aab702d5-4680-4f7a-90ae-96f3e623441e)

Currently, there is a way to set a menu to root, but is there any ways to set it as a child of user's custom menu?

**Comment by cstria0106** [comment]
안녕하세요. 옷장 메뉴를 다른 메뉴에 설치하는 기능은 현재 없습니다. 다만 반대로 기존 모듈러 아바타 메뉴를 옷장 메뉴에 설치하는것은 가능합니다 (InventoryMenuInstaller 이용)

해당 기능은 구현 예정에는 없지만 필요성을 느끼는 분들이 많은 것 같아 시간날때 구현해보려고 합니다.

**Comment by gwanryo** [comment]
Thanks!

**Comment by cstria0106** [comment]
Resolved by ad024c7
