### ISSUE TITLE
파라미터의 SAVE 속성을 해제하는 기능

### ISSUE THREAD

**Issue by Uz-Ki** [cstria0106/OneClickInventory#26]
현재로썬 다른 월드로 이동하거나, 아바타를 변경하고 다시 돌아와도 그대로 유지되게 되는 Save 속성이 파라미터에 적용이 되고 있는데 이를 해제 상태로 적용하고 싶습니다.

**Comment by cstria0106** [comment]
옵션으로 만들어보겠습니다.

**Comment by cstria0106** [comment]
Resolved by commit 97207dc
